apiVersion: v1
kind: Service
metadata:
  name: servicio-nginx-demo
spec:
  selector:
    app: nginx-demo # Debe coincidir con el Deployment
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80